 program test_cufft
    use, intrinsic :: iso_c_binding 
    use cufft_m
    ! use pressure_cpu
    use pressure
    use cudafor
    use precision
    use dimen
    implicit none

    integer istat
    ! REAL time_begin, time_end,time_gpu,time_cpu,max_error
    real(fp_kind), dimension(nx,ny,nz2) ::  txx_host,txy_host,txz_host,&
    tyy_host,tyz_host,tzz_host,LM_old_host,MM_old_host,NN_old_host,QN_old_host,cs2

    real, dimension(nx,ny,nz2) :: dudx_host,dudy_host,dudz_host,&
                                    dvdx_host,dvdy_host,dvdz_host,&
                                    dwdx_host,dwdy_host,dwdz_host

    real, dimension(nx,ny,nz2),device :: txx,txy,txz,tyy,tyz,tzz,LM_old,MM_old,NN_old,QN_old,cs2
    real, dimension(nx,ny,nz2),device :: dudx,dudy,dudz,dvdx,dvdy,dvdz,dwdx,dwdy,dwdz
    integer t
    integer Nt

    type(c_ptr) plan_batch(2)
    REAL(fp), POINTER, DIMENSION(:) :: null_ptr => NULL ()
    REAL time_begin, time_end,time_gpu,time_cpu,max_error
    type (cudaEvent) :: startEvent, stopEvent
    real*4 :: time

    t = 1
    Nt = 100
    me = 0
    nall = 0
    Print *, 'Check subroutine: press_stag.cuf'
    ! batch fft plan

    ! Create fft plan
    
    istat = cudaEventCreate(startEvent)
    istat = cudaEventCreate(stopEvent)


    call random_number(dudx_host)
    call random_number(dvdx_host)
    call random_number(dwdx_host)
    call random_number(dudy_host)
    call random_number(dvdy_host)
    call random_number(dwdy_host)
    call random_number(dudz_host)
    call random_number(dvdz_host)
    call random_number(dwdz_host)
    
    
    ! Initial variable
    call subgrid_stress(txx,txy,txz,tyy,tyz,tzz,&
                                u,v,w,&
                                dudx,dudy,dudz,&
                                dvdx,dvdy,dvdz,&
                                dwdx,dwdy,dwdz, &
                                LM_old,MM_old,QN_old,NN_old,cs2,&
                                1,me,nall)
    ! Time profiling
    istat = cudaEventRecord(startEvent, 0)
    do t = 2,Nt+1
        call subgrid_stress(txx,txy,txz,tyy,tyz,tzz,&
                                u,v,w,&
                                dudx,dudy,dudz,&
                                dvdx,dvdy,dvdz,&
                                dwdx,dwdy,dwdz, &
                                LM_old,MM_old,QN_old,NN_old,cs2,&
                                t,me,nall)
    end do 
    istat = cudaEventRecord(stopEvent, 0)
    istat = cudaEventSynchronize(stopEvent)
    istat = cudaEventElapsedTime(time, startEvent, stopEvent)
    
    print *,'Time ', time/Nt, ' ms'

end program test_cufft

