 program test_cufft
    use, intrinsic :: iso_c_binding 
    use cufft_m
    ! use pressure_cpu
    use pressure
    use cudafor
    use precision
    use mpi
    use press_cpu
    use dimen
    implicit none

    integer istat
    ! REAL time_begin, time_end,time_gpu,time_cpu,max_error
    real(fp),dimension(nx,ny,nz2):: rhs_p_host,dpdx_host,dpdy_host,p_host
    real(fp),dimension(nx,ny,nz2):: rhs_p_host1,dpdx_host1,dpdy_host1,p_host1
    real(fp),dimension(:,:,:),device, allocatable :: rhs_p,dpdx,dpdy,p
    integer t,i
    integer Nt

    type(c_ptr) plan_batch(2)
    REAL(fp), POINTER, DIMENSION(:) :: null_ptr => NULL ()
    REAL time_begin, time_end,time_gpu,time_cpu,max_error
    type (cudaEvent) :: startEvent, stopEvent
    real*4 :: time

    integer :: localRank
    character(len=10) :: rankStr
    ! MPI initialization
    call GET_ENVIRONMENT_VARIABLE ('OMPI_COMM_WORLD_LOCAL_RANK',rankStr)
    read (rankStr,'(i10)') localRank
    istat = cudaSetDevice (localRank)

    call mpi_init( ierr )
    call mpi_comm_rank( mpi_comm_world, me, ierr )
    call mpi_comm_size( mpi_comm_world, job_np, ierr )
    nall=mpi_comm_world

    print *,me,localRank
    t = 1
    Nt = 100

    Print *, 'Check subroutine: sgs.cuf'
    ! batch fft plan


    call MPI_finalize(ierr)

end program test_cufft

