program main
    use cudafor
    use cuda_graph
    use iso_c_binding
    implicit none
  
    integer :: i, n, istat
    integer(kind=cuda_stream_kind) :: stream
    integer, device, allocatable :: a(:)
    type(cudaGraph) :: graph
    type(cudaGraphExec) :: graph_exec
    type(cudaGraphNode) :: error_node
    character(c_char) :: buffer
    integer(c_size_t) :: buffer_len
  
    istat = cudaStreamCreateWithFlags(stream, cudaStreamNonBlocking)
    print*, istat
    !istat = cudaGraphCreate(graph, 0)
  
    allocate(a(1024))
  
    istat = cudaStreamBeginCapture(stream, 0)
    print*, istat
    do n = 1,1000
      !$cuf kernel do <<<*,*,stream=stream>>>
      do i = 1, 1024
        a(i) = 1234
      end do
    end do
    istat = cudaStreamEndCapture(stream, graph)
    print*, istat
  
    buffer_len = 0
    istat = cudaGraphInstantiate(graph_exec, graph, error_node, buffer, buffer_len)
    print*, istat
  
    istat = cudaGraphLaunch(graph_exec, stream)
    print*, istat
  
    istat = cudaStreamSynchronize(stream)
  
  
  end program
  