program sendrecv
    use mpi
    implicit none
  
    integer :: nthreads=1
    integer :: nproc, myrank
    integer :: tag, status(MPI_STATUS_SIZE), ierr
    integer :: token=0
    integer :: i
  
    call MPI_Init(ierr)
    call MPI_Comm_Size(MPI_COMM_WORLD, nproc, ierr)
    call MPI_Comm_Rank(MPI_COMM_WORLD, myrank, ierr)
  
    do i = 1, nproc
       call MPI_Barrier(MPI_COMM_WORLD, ierr)
       if (myrank == (i - 1)) then
          print "('My rank is: ', I2, ' on ', I2, ' total processes')" &
               , myrank, nproc
       endif
    enddo
    call MPI_Barrier(MPI_COMM_WORLD, ierr)
  
    tag = 42
    if (myrank > 0) then
       call MPI_Recv(token, 1, MPI_INTEGER, myrank-1, tag, MPI_COMM_WORLD &
           , status, ierr)
    endif
    ! call getpid(pid)
    print "('proc: ', I2)", myrank
    if (myrank < (nproc-1)) then
       call MPI_Send(token, 1, MPI_INTEGER, myrank+1, tag, MPI_COMM_WORLD, ierr)
    endif
    call MPI_Barrier(MPI_COMM_WORLD, ierr)
    call MPI_Finalize(ierr)
  
  end program sendrecv